accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path, include, reverse_lazy
from receipts.views import (
    AccountCreateView,
    ReceiptsListView,
    CategoryCreateView,
    ReceiptCreateView,
    CategoryListView,
    AccountListView,
)

urlpatterns = [
    path("", ReceiptsListView.as_view(), name="home"),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_account",
    ),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path(
        "category/create/",
        CategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "categories/",
        CategoryListView.as_view(),
        name="list_categories",
    ),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from unicodedata import category
from django.conf import settings
from django.db import models


USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()

    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        ExpenseCategory,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username = username,
                password = password,
            )
            user.save()
            login(request,user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form, 
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from unicodedata import name
from django.shortcuts import render, redirect
from django.views.generic import ListView, TemplateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Account, ExpenseCategory, Receipt


class ReceiptsListView(LoginRequiredMixin, ListView):
    template_name = "receipts/list.html"
    model = Receipt

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = [
        "vendor",
        "total",
        "tax",
        "date",
        "category",
        "account",
    ]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_accounts")


class CategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "category/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "category/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accounts</title>
</head>
<nav>
    {% if user.is_authenticated %}
    
        <a href="{% url "list_accounts" %}">Accounts</a>
        <a href="{% url "create_account" %}">Create Account</a>
        <a href="{% url "list_categories" %}">Category</a>
        <a href="{% url "create_category" %}">Create Category</a>
        <a href="{% url "home" %}">Receipts</a>
        <a href="{% url "create_receipt" %}">Create Receipt</a>
        <a href="{% url "logout" %}">logout</a>
    
    {% else %}
        <a href="{% url "signup" %}">signup</a>
        <a href="{% url "login" %}">login</a>
    {% endif %}
</nav>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="login-form">
    <h1>Create an Account</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<h2>Accounts</h2>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for account in account_list %}
        <tr>
            <td>{{ account.name }}</td>
            <td>{{ account.number }}</td>
            <td>{{ account.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

receipts/templates/category/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="login-form">
    <h1>Create a Category</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}

receipts/templates/category/list.html
{% extends 'base.html' %}

{% block content %}
<h2>Category</h2>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for category in expensecategory_list %}
        <tr>
            <td>{{ category.name }}</td>
            <td>{{ category.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="login-form">
    <h1>Create a Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<h2>Receipts</h2>
<table>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for receipt in receipt_list %}
        <tr>
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.total }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date|date:"m-d-Y" }}</td>
            <td>{{ receipt.category.name }}</td>
            <td>{{ receipt.account.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}